### PR TITLE
add sway template to the list

### PR DESCRIPTION
**Pull request by rkubosz**
As in the title. This template is based on i3 one.

### CODE REVIEW

**Comment by chriskempson** [comment]
Could you push this to https://github.com/chriskempson/base16-templates-source/ please?

**Comment by chriskempson** [comment]
Did this for you.

**Comment by rkubosz** [comment]
Hello @chriskempson...
I'm sorry that I did not to respond to you earlier. Thanks for doing it.

**Comment by chriskempson** [comment]
@rkubosz Not a problem! 👍

**Pull request closed without merging**
