### PR TITLE
Add base16-materialtheme-scheme

### PR DESCRIPTION
**Pull request by ntpeters**
Contains four themes based on https://github.com/equinusocio/material-theme

### CODE REVIEW

**Comment by chriskempson** [comment]
This is an interesting scheme to come to base16. I believe Material was originally built on base16-ocean (though there is no mention of this on the project readme anymore)?

**Comment by ntpeters** [comment]
Not sure why, but it looks like everything Ocean-based was removed last year: https://github.com/equinusocio/material-theme/commit/c7d752761d8f415ce0261cf7dc85d4d0aac9ec05

**Comment by chriskempson** [comment]
Not exactly, looking at the current https://github.com/equinusocio/material-theme/blob/develop/schemes/Material-Theme.tmTheme I believe it was very much inspired by (if not built upon) base16's textmate. It has changed much since but as I wrote that template from scratch I still recognise some parts of it 😉

I wonder if @equinusocio can shed any light on this?

**Comment by equinusocio** [comment]
Material theme is based on totally custom colors and monstly of them come from the material design palette with some small changes.. is not based on other color scheme. The oceans variants was removed time ago.

**Comment by equinusocio** [comment]
tmTheme files structure was originally generated from  https://tmtheme-editor.herokuapp.com

**Comment by chriskempson** [comment]
Thanks for the input. I guess that clears things up somewhat 👍

**Pull request merged**
