### PR TITLE
Add flavours to README

### PR DESCRIPTION
**Pull request by Misterio77**
Hello,

I just finished implementing my Rust base16 manager: https://github.com/Misterio77/flavours
The functionality is kinda a mix between base16-universal-manager and a builder (except it doesn't build to disk).

The main feature is applying schemes globally (based on your configuration, includes optional hooks) by specifying the scheme name, also supports glob matching, tab completions and a lot more. It's great for integrating into rofi menus and bar widgets (such as polybar). And it's _fast_.

Added a link to it on the readme

### CODE REVIEW

**Comment by Misterio77** [comment]
I'm not sure about the order on base16 tools, so i've put it on the top. Feel free to move it lower if it's better.

**Comment by belak** [comment]
Looks interesting! In general we keep these alphabetical.

**Comment by Misterio77** [comment]
Thanks! Moved it down to match alphabetical order.

**Comment by Misterio77** [comment]
Just wanted to let you know flavours now can also generate base16 schemes based on images. (It basically grabs colors with colorthief, searches for colors matching some criteria, corrects it to improve readability, creates the 00-07 shades, and then looks for saturated colors for the 08-0F colors). The schemes can be directly generated onto flavours folder, or output to stdout.

**Comment by Misterio77** [comment]
May be worth checking it out if you're interested c:

**Comment by belak** [comment]
Looks good to me. Thanks!

**Pull request merged**
