### PR TITLE
add iTerm2 template

### PR DESCRIPTION
**Pull request by martinlindhe**
@chriskempson, I am not sure if this is not listed due to an oversight or not?

### CODE REVIEW

**Comment by belak** [comment]
I'm pretty sure this isn't listed because it doesn't use the new builder system and hasn't been updated in about 9 months... The themes skills work but the template should be rebuilt to use the new system

**Comment by belak** [comment]
I'm pretty sure this isn't listed because it doesn't use the new builder system and hasn't been updated in about 9 months... The themes should still work but the template should be rebuilt to use the new system

**Comment by chriskempson** [comment]
That's exactly right. Could do work someone forking that repo and maintaining it as I no longer have a Mac and can't test it anymore.

**Comment by martinlindhe** [comment]
I'm having a look to see if I could update the base16-iterm repo for the new builder system

**Comment by martinlindhe** [comment]
Okay, I made some progress

Pushed to https://github.com/martinlindhe/base16-iterm2/commit/6b6f2bfd3ec8a0b39992618af255b2ddd9c4af0e

But I'm struggling with triggering a local build to verify i got it right.

I added `iterm2: https://github.com/martinlindhe/base16-iterm2` in sources/templates/list.yaml

Then, I symlinked my repo: `ln -s ~/dev/base16-iterm2 templates/iterm2`

This works, but is there an easier way to do this?

Also, I am having trouble figuring out how the previous iterm2 files were generated,
there is `light` and `dark` variations, and they can be in 256 colors.

I think I nailed the 16-color dark variation in the linked commit, but cannot easily diff the output because of variations in naming, and also in the rounding of the values in the generated files (iTerm uses the `{{base00-dec-b}}` format)

Any pointers appreciated!

Also,

**Comment by belak** [comment]
With the old builder, each theme had an implicit light and dark variant. That isn't the case any more, so you shouldn't need to worry as much about that. They were previously generated using this repo: https://github.com/chriskempson/base16-builder

**Comment by martinlindhe** [comment]
@belak perfect! I was semi-guessing color mapping, I now found https://github.com/chriskempson/base16-builder/blob/master/templates/iterm2/dark.itermcolors.erb etc which was the last missing piece!

**Comment by belak** [comment]
I'd strongly recommend only providing a normal and a 256 color variant because the dark themes should be provided as separate scheme files now if they are meant to have one.

**Comment by martinlindhe** [comment]
Thanks, was just about to ask about that :-)

**Comment by martinlindhe** [comment]
Okay, I think i completed the update.

https://github.com/martinlindhe/base16-iterm2/commit/9a094809cf3dd9857b4d82b77f67afe729809ea1

**Comment by martinlindhe** [comment]
@chriskempson, I could maintain the base16-iterm2

I forked and updated it for builder 0.9 at https://github.com/martinlindhe/base16-iterm2

Would you like me to send a PR to https://github.com/chriskempson/base16-iterm2, or should I keep it as a fork?

When that's decided, I'll go ahead and update this PR + send an addition to https://github.com/chriskempson/base16-templates-source

Anything I missed?


@belak, thank you very much for your quick help!

**Comment by chriskempson** [comment]
All looks good. It's probably best your keep it as a fork and become the official maintainer for it 😉

**Comment by martinlindhe** [comment]
Okay, updated this PR to instead list me as maintainer, and link to https://github.com/martinlindhe/base16-iterm2

**Comment by martinlindhe** [comment]
Related pr: https://github.com/chriskempson/base16-templates-source/pull/35

**Pull request merged**
